[workspace]
members = ["proto-build", "juno-rust-proto", "tests/*"]

[profile.release.package.oracle-querier]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false