
name: juno-rust-proto

on:
  push:
    branches: main
  pull_request:
    paths:
      - "juno-rust-proto/**"
      - "Cargo.*"

defaults:
  run:
    working-directory: juno-rust-proto

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.59.0 # MSRV
          - stable
        target:
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
